<?php

$img = static fn (string $id, int $w = 900, int $h = 600): string => "https://images.unsplash.com/{$id}?w={$w}&h={$h}&fit=crop&q=80";

return [
    'carousel_count' => 4,
    'categories' => [
        ['key' => 'suite', 'title' => 'Suites', 'subtitle' => 'Prestige & raffinement'],
        ['key' => 'familiale', 'title' => 'Chambres Familiales', 'subtitle' => 'Confort pour toute la famille'],
        ['key' => 'single', 'title' => 'Chambres Singles', 'subtitle' => 'Élégance et simplicité'],
    ],
    'rooms' => [
        ['num' => '401', 'type' => 'suite', 'floor' => 4, 'title' => 'Suite Royale', 'desc' => 'Terrasse privée, jacuzzi et vue panoramique.', 'longDesc' => 'Notre Suite Royale offre un espace généreux avec terrasse privée, jacuzzi et une vue imprenable sur la ville. Service premium et finitions luxueuses pour un séjour d\'exception.', 'price' => 3000, 'img' => $img('photo-1631049307264-da0ec9d70304')],
        ['num' => '402', 'type' => 'suite', 'floor' => 4, 'title' => 'Suite Présidentielle', 'desc' => 'Grand salon et service majordome 24h/24.', 'longDesc' => 'La Suite Présidentielle dispose d\'un grand salon, d\'un bureau exécutif et d\'un service majordome disponible à toute heure.', 'price' => 2800, 'img' => $img('photo-1582719478250-c89cae4dc85b')],
        ['num' => '301', 'type' => 'suite', 'floor' => 3, 'title' => 'Suite Junior', 'desc' => 'Salon séparé et vue mer partielle.', 'longDesc' => 'Suite Junior élégante avec salon indépendant, minibar premium et vue mer partielle.', 'price' => 1100, 'img' => $img('photo-1611892440504-42a792e3848b')],
        ['num' => '302', 'type' => 'suite', 'floor' => 3, 'title' => 'Suite Executive', 'desc' => 'Idéale pour voyages d\'affaires premium.', 'longDesc' => 'Espace travail ergonomique, wifi fibre et salon privé. La suite idéale pour les voyageurs d\'affaires exigeants.', 'price' => 1350, 'img' => $img('photo-1590490360182-c33d5d3baeae')],
        ['num' => '501', 'type' => 'suite', 'floor' => 5, 'title' => 'Suite Panoramique', 'desc' => 'Vue 360° sur les jardins et la médina.', 'longDesc' => 'Admirez un panorama à 360° depuis cette suite exceptionnelle. Lumière naturelle et décoration contemporaine.', 'price' => 2200, 'img' => $img('photo-1566665797739-1674de7a421a')],
        ['num' => '502', 'type' => 'suite', 'floor' => 5, 'title' => 'Suite Diplomatique', 'desc' => 'Réception privée et salle à manger.', 'longDesc' => 'Réception privée, chambre d\'appoint et salle à manger pour recevoir dans les meilleures conditions.', 'price' => 1950, 'img' => $img('photo-1522771739844-6a9f6d5f14af')],
        ['num' => '115', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Confort', 'desc' => 'Deux lits doubles et coin jeux enfants.', 'longDesc' => 'Chambre familiale spacieuse avec deux lits doubles, coin jeux pour enfants et salle de bain moderne.', 'price' => 950, 'img' => $img('photo-1591088398332-8a7791972843')],
        ['num' => '116', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Plus', 'desc' => 'Chambres communicantes modulables.', 'longDesc' => 'Configuration flexible avec chambres communicantes et canapé-lit supplémentaire.', 'price' => 1050, 'img' => $img('photo-1578683010236-d716f9a3f461')],
        ['num' => '117', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Jardin', 'desc' => 'Accès direct au jardin ombragé.', 'longDesc' => 'Accès direct au jardin, terrasse ombragée et calme absolu pour des vacances en famille ressourçantes.', 'price' => 980, 'img' => $img('photo-1595577507911-781ad1cec561')],
        ['num' => '118', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Deluxe', 'desc' => 'Kitchenette et deux salles de bain.', 'longDesc' => 'Mini-suite familiale haut de gamme avec kitchenette équipée et deux salles de bain.', 'price' => 1200, 'img' => $img('photo-1596394516093-501ba68a0ba6')],
        ['num' => '119', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Twin', 'desc' => 'Lits jumeaux modulables.', 'longDesc' => 'Configuration lits jumeaux modulable selon vos besoins. Parfaite pour familles avec adolescents.', 'price' => 920, 'img' => $img('photo-1584132960404-1e4d77facb69')],
        ['num' => '120', 'type' => 'familiale', 'floor' => 1, 'title' => 'Familiale Premium', 'desc' => '45 m² avec salle de bain familiale.', 'longDesc' => '45 m² d\'espace soigneusement aménagé, salle de bain familiale spacieuse et literie premium.', 'price' => 1100, 'img' => $img('photo-1505693416388-ac5ce068fe85')],
        ['num' => '101', 'type' => 'single', 'floor' => 1, 'title' => 'Simple Standard', 'desc' => 'Lit queen et salle de bain moderne.', 'longDesc' => 'Chambre single confortable avec lit queen, climatisation et salle de bain moderne.', 'price' => 450, 'img' => $img('photo-1618773928121-c32242e63f39')],
        ['num' => '102', 'type' => 'single', 'floor' => 1, 'title' => 'Simple Économique', 'desc' => 'Confort essentiel au meilleur prix.', 'longDesc' => 'Confort essentiel au meilleur rapport qualité-prix. Idéale pour courts séjours.', 'price' => 380, 'img' => $img('photo-1551882547-ff40c63fe5fa')],
        ['num' => '103', 'type' => 'single', 'floor' => 1, 'title' => 'Simple Vue Jardin', 'desc' => 'Calme et verdure, patio privé.', 'longDesc' => 'Calme et verdure, rez-de-chaussée avec patio. Une parenthèse nature en ville.', 'price' => 420, 'img' => $img('photo-1560185127-6ed189bf02f4')],
        ['num' => '104', 'type' => 'single', 'floor' => 1, 'title' => 'Simple Cosy', 'desc' => 'Décoration chaleureuse et parquet noble.', 'longDesc' => 'Ambiance chaleureuse, parquet noble et éclairage tamisé pour un repos parfait.', 'price' => 440, 'img' => $img('photo-1540518614846-7eded433c457')],
        ['num' => '105', 'type' => 'single', 'floor' => 1, 'title' => 'Simple Business', 'desc' => 'Bureau ergonomique et wifi fibre.', 'longDesc' => 'Bureau ergonomique, wifi fibre et check-in express pour les voyageurs pressés.', 'price' => 490, 'img' => $img('photo-1598928506311-c55ded91a2c2')],
        ['num' => '201', 'type' => 'single', 'floor' => 2, 'title' => 'Simple Supérieure', 'desc' => 'Étage élevé et literie premium.', 'longDesc' => 'Étage élevé, literie premium et vue dégagée sur les environs.', 'price' => 520, 'img' => $img('photo-1590071243278-1a27d934d92f')],
        ['num' => '202', 'type' => 'single', 'floor' => 2, 'title' => 'Simple Lumineuse', 'desc' => 'Grande baie vitrée, lumière naturelle.', 'longDesc' => 'Baignée de lumière naturelle grâce à sa grande baie vitrée toute la journée.', 'price' => 480, 'img' => $img('photo-1560448204-e02f11c3d0e2')],
        ['num' => '203', 'type' => 'single', 'floor' => 2, 'title' => 'Simple Zen', 'desc' => 'Ambiance apaisante et minimaliste.', 'longDesc' => 'Ambiance apaisante, aromathérapie et décoration minimaliste pour une détente totale.', 'price' => 460, 'img' => $img('photo-1598887157202-a35a8370731e')],
        ['num' => '204', 'type' => 'single', 'floor' => 2, 'title' => 'Simple City View', 'desc' => 'Vue urbaine dégagée.', 'longDesc' => 'Vue urbaine dégagée, idéale pour courts séjours en centre-ville.', 'price' => 500, 'img' => $img('photo-1571003123894-1f0594d2b5d9')],
        ['num' => '205', 'type' => 'single', 'floor' => 2, 'title' => 'Simple Deluxe', 'desc' => 'Mini-bar et articles de toilette luxe.', 'longDesc' => 'Mini-bar, peignoirs moelleux et articles de toilette haut de gamme.', 'price' => 550, 'img' => $img('photo-1586023492125-27b2c045efd7')],
    ],
];
